#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#ifndef RATING_DECIMALS_OPT
#define RATING_DECIMALS_OPT 4
#endif

#ifndef PRE_DOT_RATING_OPT
#define PRE_DOT_RATING_OPT 5
#endif

#ifndef PAYMENT_DECIMALS_OPT
#define PAYMENT_DECIMALS_OPT 2
#endif

#ifndef PRE_DOT_PAYMENT_OPT
#define PRE_DOT_PAYMENT_OPT 7
#endif



enum constants
{
    RATING_DECIMALS = RATING_DECIMALS_OPT,
    PAYMENT_DECIMALS = PAYMENT_DECIMALS_OPT,
    PRE_DOT_PAYMENT = PRE_DOT_PAYMENT_OPT,
    PRE_DOT_RATING = PRE_DOT_RATING_OPT
};

#endif
